TOP_DIR = ..
MODULE_TOP_DIR = .
BUILD_TYPE = bin
BUILD_NAME = sample
SUB_MOD =
SUB_DIR = 
DEP_LIBS_LIST += $(TOP_DIR)/build/lib/libengine.so $(TOP_DIR)/build/lib/libdecoder.so
LDFLAGS_LOCAL = -lstdc++

include $(TOP_DIR)/script/compile.mk

